/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import chatServer.chatServer;
import java.io.BufferedInputStream;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.io.OutputStreamWriter;
import java.net.ServerSocket;
import java.net.Socket;
import java.util.List;
import java.util.Set;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lhqua
 */
public class FormServer extends javax.swing.JFrame {

    private chatServer cServer = null;
    private ServerSocket serverSocket = null;
    private final int BUFFER_SIZE = 100;
    private static final int CHUNK_SIZE = 1024;
    /**
     * Creates new form FormServer
     */
    public FormServer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        layPort = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        bangTinNhan = new javax.swing.JTextArea();
        start = new javax.swing.JButton();
        test = new javax.swing.JButton();
        thoat = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        danhSachKetNoi = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Chat Server");

        jLabel3.setText("Port");

        layPort.setText("3200");

        bangTinNhan.setColumns(20);
        bangTinNhan.setRows(5);
        jScrollPane1.setViewportView(bangTinNhan);

        start.setText("Start");
        start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startActionPerformed(evt);
            }
        });

        test.setText("Test");
        test.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testActionPerformed(evt);
            }
        });

        thoat.setText("Thoát");
        thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thoatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(start, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(thoat, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(test, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(layPort, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(layPort, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(start)
                    .addComponent(test)
                    .addComponent(thoat))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Danh Sách Client Online");

        danhSachKetNoi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null}
            },
            new String [] {
                "Tài Khoản"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(danhSachKetNoi);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel4))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(51, 51, 51)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void thoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thoatActionPerformed
        int confirm = JOptionPane.showConfirmDialog(null, " Bạn Có Muốn Thoát Không ?");
        if (confirm == 0) {
            try {
                serverSocket.close();
            } catch (IOException ex) {
                Logger.getLogger(FormServer.class.getName()).log(Level.SEVERE, null, ex);
            }
            System.exit(0);
        }

    }//GEN-LAST:event_thoatActionPerformed

    private void testActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testActionPerformed
        int port = Integer.valueOf(layPort.getText());

        bangTinNhan.append("\nStart Thành Công Tại IP: 127.0.0.1");
        bangTinNhan.append("\nStart Thành Công Tại Port: " + port);
        System.out.println("Test");
    }//GEN-LAST:event_testActionPerformed

    private void startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startActionPerformed
        start.setEnabled(false);
        if (layPort.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Chưa Nhập Port");
            return;
        }

        int port = Integer.valueOf(layPort.getText());
        cServer = new chatServer(port);
        try {
            serverSocket = new ServerSocket(port);
            execute();
            bangTinNhan.append("\nStart Thành Công Tại Port: " + port);
            Thread thread = new Thread() {
                public void run() {

                    while (true) {
                        try {

                            Socket socket = serverSocket.accept();

                            cServer.addSocket(socket);
                            readServer(socket);

                        } catch (IOException ex) {
                            Logger.getLogger(FormServer.class.getName()).log(Level.SEVERE, null, ex);
                            bangTinNhan.append("\nError!!");
                        }
                    }
                }
            };
            thread.start();
        } catch (IOException ex) {
            Logger.getLogger(FormServer.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.err.println("hihi3");
    }//GEN-LAST:event_startActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormServer().setVisible(true);
            }
        });
    }

    private void readServer(Socket socketClient) throws IOException {
        Thread thread = new Thread() {
            @Override
            public void run() {
                DataInputStream dis = null;

                try {
                    dis = new DataInputStream(socketClient.getInputStream());
                    while (true) {
                        String sms = dis.readUTF();
                        int test = 0;
                        System.out.println(sms);
                        StringTokenizer token = new StringTokenizer(sms);
                        String Format = token.nextToken();
                        System.out.println(Format);
                        
                        switch (Format) {
                            case "ThongTin": {
                                String nameUser = token.nextToken();
                                cServer.addUserName(nameUser);
                                capNhatDanhSachOnl();
                                writeServer();
                                bangTinNhan.append("\nTài Khoản: " + nameUser + " Đã Kết Nối");
                                break;
                            }
                            case "Thoat": {
                                String nameUser = token.nextToken();
                                int idex = -1;
                                for (int i = 0; i < cServer.getUserNames().size(); i++) {
                                    if (cServer.getUserNames().get(i).equals(nameUser)) {
                                        idex = i;
                                        break;
                                    }
                                }
                                System.out.println(idex);
                                if (idex != -1) {
                                    if (!cServer.removeUser(cServer.getUserNames().get(idex), cServer.getListSocket().get(idex))) {
                                        JOptionPane.showMessageDialog(null, "Không Cập Nhật Danh Sách Client Onl Được");
                                    }
                                }
                                bangTinNhan.append("\nTài Khoản: " + nameUser + " Đã Thoát");
                                capNhatDanhSachOnl();
                                writeServer();
                                break;
                            }
                            case "ChatAll": {
                                String userSend = token.nextToken();
                                writeAll(userSend, sms);
                                
                                break;
                            }
                            case "ChatOneOne": {
                                String smsReceive = sms;
                                String userSend = token.nextToken();
                                String userReceive = token.nextToken();
                                writeOneOne(userSend, userReceive, sms);
                                break;
                            }
                            case "SEND_FILE": {
                                String fileName = token.nextToken();
                                String stFileSize = token.nextToken();
                                String userSend = token.nextToken();
                                String userReceive = token.nextToken();
                                File file = new File("./download/",fileName);
                                int indexSend = -1;
                                    for (int i = 0; i < cServer.getUserNames().size(); i++) {
                                        if (cServer.getUserNames().get(i).equals(userSend)) {
                                            indexSend = i;
                                            break;
                                        }
                                    }
                                saveFile(file,cServer.getListSocket().get(indexSend).getInputStream() );
                                    
                                
                                int index = -1;
                                    for (int i = 0; i < cServer.getUserNames().size(); i++) {
                                        if (cServer.getUserNames().get(i).equals(userReceive)) {
                                            index = i;
                                            break;
                                        }
                                    }
                                if(index != -1){
                                    DataOutputStream dos = new DataOutputStream(cServer.getListSocket().get(index).getOutputStream());
                                    String tmp ="SEND_FILE" + " " + fileName + " " + stFileSize + " " + userSend + " " + userReceive;
                                    dos.writeUTF(tmp);
                                    
                                    writeFile(file,dos);
                                    System.out.println("Finished sending " + file.getName() + " to client");
                                    
                                }   
                                System.out.println("Finished sending " + file.getName() + " to server");
                                break;
                            }

                            default:
                                

                                System.out.println("huhu");
                                //bangTinNhan.append(sms);
                                break;
                        }

                    }
                } catch (IOException ex) {
                    ex.printStackTrace();
                    try {
                        dis.close();
                        socketClient.close();
                    } catch (IOException ex1) {
                        ex1.printStackTrace();
                    }

                }

            }
        };
        thread.start();
    }

    private void writeFile(File file,OutputStream outStream){
        //Tham Khao
        FileInputStream reader = null;
        try {
            reader = new FileInputStream(file);
            byte[] buffer = new byte[CHUNK_SIZE];
            int pos = 0;
            int bytesRead;
            while ((bytesRead = reader.read(buffer, 0, CHUNK_SIZE)) >= 0) {
                outStream.write(buffer, 0, bytesRead);
                outStream.flush();
                pos += bytesRead;
                System.out.println(pos + " bytes (" + bytesRead + " bytes read)");
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(FormServer.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(FormServer.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            if (reader != null) {
                try {
                    reader.close();
                } catch (IOException ex) {
                    Logger.getLogger(FormServer.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }
    private void saveFile(File file, InputStream inStream) {
        //Tham Khao
        FileOutputStream fileOut = null;
        
        try {
            fileOut = new FileOutputStream(file);
            byte[] buffer = new byte[CHUNK_SIZE];
            int bytesRead;
            int pos = 0;
            while ((bytesRead = inStream.read(buffer, 0, CHUNK_SIZE)) > 0) {
                pos += bytesRead;
                System.out.println(pos + " bytes (" + bytesRead + " bytes read)");
                fileOut.write(buffer, 0, bytesRead);
                if(bytesRead <1024){
                    break;
                }
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(FormServer.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(FormServer.class.getName()).log(Level.SEVERE, null, ex);
        }finally{
            if (fileOut != null) {
                try {
                    fileOut.close();
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
        }
        System.out.println("Finished, filesize = " + file.length());
    }
    private void writeServer() {
        Thread thread = new Thread() {
            @Override
            public void run() {
                DataOutputStream dos = null;
                //Scanner sc = null;
                try {
                    String sms = "UserOnl";
                    for (String user : cServer.getUserNames()) {
                        sms = sms + " " + user;
                    }
                    for (Socket i : cServer.getListSocket()) {
                        dos = new DataOutputStream(i.getOutputStream());
                        dos.writeUTF(sms);
                    }
                } catch (IOException ex) {
                    ex.printStackTrace();
                    try {
                        dos.close();

                    } catch (IOException ex1) {
                        ex1.printStackTrace();

                    }
                }
            }
        };
        thread.start();
    }

    private void writeOneOne(String userSend, String userReceive, String sms) {
        Thread thread = new Thread() {
            @Override
            public void run() {
                DataOutputStream dos = null;
                //Scanner sc = null;
                try {
                    int index = -1;
                    for (int i = 0; i < cServer.getUserNames().size(); i++) {
                        if (cServer.getUserNames().get(i).equals(userReceive)) {
                            index = i;
                            break;
                        }
                    }
                    if (index != -1) {
                        dos = new DataOutputStream(cServer.getListSocket().get(index).getOutputStream());
                        dos.writeUTF(sms);
                    }
                } catch (IOException ex) {
                    ex.printStackTrace();
                    try {
                        dos.close();

                    } catch (IOException ex1) {
                        ex1.printStackTrace();

                    }
                }
            }
        };
        thread.start();
    }
    
    private void writeAll(String userSend, String sms){
        Thread thread = new Thread() {
            @Override
            public void run() {
                DataOutputStream dos = null;
                
                try {

                    for (int i = 0; i < cServer.getListSocket().size(); i++) {
                        if (!cServer.getUserNames().get(i).equals(userSend)) {
                            dos = new DataOutputStream(cServer.getListSocket().get(i).getOutputStream());
                            dos.writeUTF(sms);
                        }
                    }
                } catch (IOException ex) {
                    ex.printStackTrace();
                    try {
                        dos.close();

                    } catch (IOException ex1) {
                        ex1.printStackTrace();

                    }
                }
            }
        };
        thread.start();
    }
    
    private void execute() throws IOException {

    }

    private void capNhatDanhSachOnl() {
        DefaultTableModel defaultTableModel = new DefaultTableModel();
        danhSachKetNoi.setModel(defaultTableModel);
        defaultTableModel.addColumn("Tài Khoản");
        List<String> danhSachOnl = cServer.getUserNames();
        for (String i : danhSachOnl) {
            Object[] tmp = new Object[]{i};
            defaultTableModel.addRow(tmp);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea bangTinNhan;
    private javax.swing.JTable danhSachKetNoi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField layPort;
    private javax.swing.JButton start;
    private javax.swing.JButton test;
    private javax.swing.JButton thoat;
    // End of variables declaration//GEN-END:variables
}
